
# ==================== BACKBONE CONFIGURATION ===============
backbone:
  architecture: "4detr-only"
  bbox-backbone: "vote"
  input-bbox: "early-concat"
  droupout-branch-fusion: true
  group-norm: false
  fancy-velocity-prediction: false
  size-bin-loss-type: "gt-backprop"
  size_pct_thresh: 1.0
  size_loss_weights:
    - 1.0
    - 1.0
    - 1.0
  use-input-box-size: false

  in-out-features:
    transformer-feat-size: 256
    pointnet-feat-size: 256
    augment-quad: true
    augment-pairs: true


  procrustes:
    proc-hinge:
      - 0.005
      - 0.005
      - 0.005
    proc-use-weights: false


  transformer-args:
    enc_dim: 256
    enc_nhead: 4
    enc_ffn_dim: 128
    enc_dropout: 0.1
    enc_activation: "relu"
    enc_nlayers: 4
    fps_max_points: 10
    fps_min_points: 5
    fps_sample_ratio: 0.5
    radius:
      car: 1.5
      pedestrian: 0.6
      motorcycle: 0.7
      vehicle: 1.5
    posenc_style: "concat-xyzt"
    posenc_use_boxfeats: true
    preenc_use_boxfeats: true
    use_attention: true



# ==================== DATA AUGMENTATION CONFIGURATION ===============
data_augmentation:
  bbox-rotation-noise:
    - -0.2
    - 0.2
  bbox-rotation-noise-per-frame:
    - -0.1
    - 0.1
  bbox-scale-noise:
    - 0.9
    - 1.1
  bbox-translation-noise:
    - -0.15
    - 0.15
  bbox-translation-noise-per-frame:
    - -0.1
    - 0.1
  crop-center-pct:
    - -0.09
    - 0.09
  crop-frame-center-pct:
    - -0.025
    - 0.025
  crop-frame-wlh-pct:
    - -0.05
    - 0.05
  crop-frame-yaw-rad:
    - -0.157
    - 0.157
  crop-wlh-pct:
    - 0.45
    - 0.75
  crop-yaw-rad:
    - -0.39
    - 0.39
  point-rotation-noise:
    - -1.57
    - 1.57
  point-scale-noise:
    - 0.95
    - 1.05
  train-augment: true
  train-augment-bboxes: true
  train-crop: false
  train-shift-augment: true


# ==================== TRAINING DATALOADING CONFIGURATION ===============
training_dataloading:
  dataset-properties:
    dataset-source: nuscenes
    frame-hz: 20
    tracking-mode: false
    use-data-cache: false
    use-zipfile: true
  sequence-filters:
    confidence-threshold: 0.0
    min-frame-pts: 1
    min-labeled-pts: 1
    min-seq-pts: 1
    only-moving-objects: false
    overlap-threshold: 15
    permitted-frame-skips: 39
  sequence-properties:
    allow-false-positive-frames: true
    backward: false
    ego-correct-coordinates: true
    max-num-pts: 256
    min-keyframes: 1
    seqs-span-many-keyframes: true
    sequence-length: 40

# ==================== TESTING DATALOADING CONFIGURATION ===============
testing_dataloading:
  dataset-properties:
    dataset-source: nuscenes
    frame-hz: 20
    tracking-mode: true
    use-data-cache: false
    use-zipfile: false
  sequence-filters:
    confidence-threshold: 0.0
    min-frame-pts: 1
    min-labeled-pts: 1
    min-seq-pts: 1
    only-moving-objects: false
    overlap-threshold: 10
    permitted-frame-skips: 11
  sequence-properties:
    allow-false-positive-frames: true
    backward: false
    ego-correct-coordinates: true
    max-num-pts: 256
    min-keyframes: 1
    seqs-span-many-keyframes: false
    sequence-length: 10


# ================== GENERAL PARAMETERS =====================
general:
  batch_size: 40
  data_root: /home/colton/Documents/SpOT-material/datasets/02-12-22-nuscenes-centerpoint
  dataset_name: nuscenes
  evaluation:
    nuscenes-path: /media/colton/ColtonSSD/nuscenes-raw
    nuscenes-version: v1.0-trainval
    waymo-detection-eval-executable: ""
    waymo-gt-file: ""
    waymo-tracking-eval-executable: ""
  lr: 0.002
  max_pnts_per_batch: 90000
  object_class: pedestrian
  only_val: false
  only_viz: false
  out: ./out/03-08-22-megvii-noauto
  parallel: false
  weights: /home/colton/Documents/SpOT-material/models/03-08-final-models/ped-final-nuscenes.pth


# ================== TRAINING LOSSES ======================
losses:
  other:
    classification-temperature:
      bicycle: 1.0
      bus: 0.5
      car: 0.75
      motorcycle: 1.0
      pedestrian: 1.0
      trailer: 0.75
      truck: 0.5
    classification-worst-ratio:
      bicycle: 0.9
      bus: 0.9
      car: 0.7
      motorcycle: 0.9
      pedestrian: 0.85
      trailer: 0.9
      truck: 0.9
  usage:
    bbox-regression: true
    classification: true
    cnf-loss: false
    segmentation-loss: true
  weight:
    bbox-center-height-residuals: 7.0
    bbox-center-xy-residuals: 8.0
    bbox-regress-size-bin: 50.0
    bbox-size-residuals: 5.0
    bbox-velocity-residuals: 4.0
    bbox-yaw-residuals: 8.0
    classification: 6
    cnf-loss: 0.005
    segmentation-loss: 5.0


# ==================== SCHEDULING =============================
scheduling:
  data-loading:
    num-workers: 16
  logging:
    print-every: 10
    save-every: 2
    track-every: 1
    val-every: 2
  optimizer:
    betas:
      - 0.9
      - 0.999
    decay: 0.97
    epochs: 200
    eps: 1.0e-08
    type: adam
  other:
    train-autoregressive: false


# ================== TRACK ASSOCIATION PARAMS ======================
track_association:
  box-affinity:
    distance-metric: l2
    iou-threshold: 0.05
    l2-distance-thresholds:
      bicycle: 3
      bus: 5.5
      car: 4
      motorcycle: 13
      pedestrian: 1
      trailer: 3
      truck: 4
      vehicle: 0.8
  matching:
    algorithm: greedy
    compare-which-frames: earliest-detection
    greedy-sort-by: detections



# ================== TRACK MANAGEMENT PARAMS ======================
track_management:
  nms:
    threshold: 0.315
    when: before-refinement
  refinement:
    age-refinement-threshold: 3
    auto-regressive-refinement: true
    confidence-anneal-rate: 1.0
    confidence-refinement-threshold: 0.0
    refinement-components: confidences-and-boxes
    refinement-strategy: tracks-only
  track-maintenance:
    max-seq-pts: null
    max-time-window: 2.0
    min-hits-usability: 0
    no-hits-kill-thresh: 3
    track-initialization-conf-thresh: 0.0


# ================== TRACKING MOTION-MODEL PARAMS ======================
track_motion_model:
  relative_time_context: 0.215
  time_context: 1.5

